steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t northamerica-south1-docker.pkg.dev/trabajo-grado-461205/taskmate/auth-ms -f Dockerfile.prod --platform=linux/amd64 .
  secretEnv: ['NATS_SERVERS', 'JWT_SECRET', 'MAIL_USERNAME', 'MAIL_PASSWORD', 'MAIL_HOST', 'AUTH_PORT', 'SALT', 'FRONTEND_URL', 'AUTH_DB_HOST', 'AUTH_DB_PORT', 'AUTH_DB_USERNAME', 'AUTH_DB_PASSWORD', 'AUTH_DB_DATABASE']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'northamerica-south1-docker.pkg.dev/trabajo-grado-461205/taskmate/auth-ms',
    ]
    
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/495852363735/secrets/NATS_SERVERS/versions/latest
    env: 'NATS_SERVERS'
  - versionName: projects/495852363735/secrets/JWT_SECRET/versions/latest
    env: 'JWT_SECRET'
  - versionName: projects/495852363735/secrets/MAIL_USERNAME/versions/latest
    env: 'MAIL_USERNAME'
  - versionName: projects/495852363735/secrets/MAIL_PASSWORD/versions/latest
    env: 'MAIL_PASSWORD'
  - versionName: projects/495852363735/secrets/MAIL_HOST/versions/latest
    env: 'MAIL_HOST'
  - versionName: projects/495852363735/secrets/AUTH_PORT/versions/latest
    env: 'AUTH_PORT'
  - versionName: projects/495852363735/secrets/SALT/versions/latest
    env: 'SALT'
  - versionName: projects/495852363735/secrets/FRONTEND_URL/versions/latest
    env: 'FRONTEND_URL'
  - versionName: projects/495852363735/secrets/AUTH_DB_HOST/versions/latest
    env: 'AUTH_DB_HOST'
  - versionName: projects/495852363735/secrets/AUTH_DB_PORT/versions/latest
    env: 'AUTH_DB_PORT'
  - versionName: projects/495852363735/secrets/AUTH_DB_USERNAME/versions/latest
    env: 'AUTH_DB_USERNAME'
  - versionName: projects/495852363735/secrets/AUTH_DB_PASSWORD/versions/latest
    env: 'AUTH_DB_PASSWORD'
  - versionName: projects/495852363735/secrets/AUTH_DB_DATABASE/versions/latest
    env: 'AUTH_DB_DATABASE'