services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: testing-db
