services:

  postgres:
    image: postgres:16
    container_name: auth-ms-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authDB
